### ISSUE TITLE
How about adding pandora and Anesidora to the repo?

### ISSUE THREAD

**Issue by DarthMDev** [ToontownRewritten/ToontownReleaseArchive#1]

**Comment by hunterboppen** [comment]
its an archive

**Comment by JoeyZio** [comment]
It's definitely something that was considered, but ultimately this archive is for _public_ releases of Toontown Online. Considering they come from leaks rather than public releases, they're also a bit riskier to host and potentially more prone to a takedown notice from Disney. Luckily, they are already on GitHub elsewhere!

https://github.com/satire6/Anesidora
https://github.com/satire6/Spotify
